### PR TITLE
optionally colorize output with -c,--color

### PR DESCRIPTION
**Pull request by scriada**
Since `line_profiler` already depends on `IPython`, thought it would be nice to use the built-in syntax highlighter when printing output.

### CODE REVIEW

**Comment by rkern** [comment]
`line_profiler` supports `IPython`, but it does not depend on `IPython`. One can install and use `line_profiler` without `IPython`.

**Comment by scriada** [comment]
@rkern but IPython is listed in `install_requires` in the _setup.py_, doesn't this mean it is considered a dependency? There are lots of `import IPython...` statements in _line_profiler.py_ so I assumed that it was safe to add another.

**Comment by rkern** [comment]
Yeah, that shouldn't have been done that way.

**Comment by caethan** [comment]
Sorry, @rkern, that was my doing as a part of updating for compatibility with IPython 5.0.  I'll take a look at it again and see if there's a way to maintain compatibility without requiring a top-level ipython import.

**Pull request closed without merging**
