### PR TITLE
Don't trust "import builtins" to check for python3

### LINKED ISSUE #12: Explicitly check for Python 3 for deciding on `builtins` import
The [`future`](https://pypi.python.org/pypi/future) package provides a `builtins` module that masquerades as a Python 3 `builtins` module, but it is a read-only namespace. Injecting into it doesn't affect the actual `__builtin__` namespace.

### LINKED ISSUE #24: "kernprof -l -v sample.py" does not recognize decorator @profile
line_profiler installed in anaconda distribution. %lprun runs fine.
however, when I try to kerprof in the following situation:

# file: primes.py
@profile
def primes(n): 
    if n==2:
        return [2]
    elif n<2:
        return []
    s=range(3,n+1,2)
    mroot = n ** 0.5
    half=(n+1)/2-1
    i=0
    m=3
    while m <= mroot:
        if s[i]:
            j=(m*m-3)/2
            s[j]=0
            while j<half:
                s[j]=0
                j+=m
        i=i+1
        m=2*i+3
    return [2]+[x for x in s if x]

primes(100)

in terminal:
kernprof -l -v primes.py

has the following info:
Wrote profile results to primes.py.lprof
Timer unit: 1e-06 s

Traceback (most recent call last):
  File "/Users/Retina/anaconda/envs/py2k/bin/kernprof", line 9, in <module>
    load_entry_point('line-profiler==1.0', 'console_scripts', 'kernprof')()
  File "build/bdist.macosx-10.5-x86_64/egg/kernprof.py", line 221, in main
  File "primes.py", line 8, in <module>
    @profile
NameError: name 'profile' is not defined

### PR DESCRIPTION
**Pull request by Nodd**
Fixes #12
Fixes #24

### CODE REVIEW

**Comment by rkern** [comment]
Thank you!

**Comment by tastyminerals** [comment]
I have just installed this module via `pip2 install line-profiler` and I still experience this issue.
I have `from __future__ import division` in my script.
How can I fix this?

**Comment by Nodd** [comment]
What issue do you have exactly ?
Also, the `future` package is not the same as importing from `__future__`, both are unrelated.

**Comment by tastyminerals** [comment]
1. insert `@profile` above the function
2. run the file with `kernprof2 -l model.py`
```
File "model.py", line 66, in <module>
    @profile
NameError: name 'profile' is not defined
```

**Comment by rkern** [comment]
Do you have the `future` package installed? Have you tried the `master` branch?

**Comment by tastyminerals** [comment]
Yes
```
Requirement already satisfied (use --upgrade to upgrade): future in /usr/lib/python2.7/site-packages
```
No, I installed `line_profiler` with `pip2` and followed the man instructions.

**Comment by rkern** [comment]
Okay, then this is fixed for you in master by this merged PR.

**Comment by tastyminerals** [comment]
Yes, if I install `line_profiler` from repo, it works. Thanks!

**Pull request merged**
